# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e7bceb204a733d7bd50f660e83dc50e36c7c06621a92ecc3a78e880c5b857bbc894aa833a398d378cc0a0833797b0c53dfdaaf5fc555585804b5223803a9a1

test:
  secret_key_base: 4a792572ccf0a6dc713d9bea3dd96189d3708b2f54a308d5f8eb7cec02b523c2ce3178e531e47672d8563eeb6fffc030dde203cf4744c42e675f1f81a7a626a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
